blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/almas-codes/request-cinema/discussions
    about: Ask questions, share ideas, and connect with other Request Cinema users.
